---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafdrop-kafka-properties
  namespace: kafdrop
data:
  kafka.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafdrop" password="YKQWu0BNb6Wzx6Ku447QxZu0o5UJedAP";
