replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

kafka:
  brokerConnect: "kafka-kafka-bootstrap.strimzi.svc.cluster.local:9092"
  properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafdrop" password="YKQWu0BNb6Wzx6Ku447QxZu0o5UJedAP";
  propertiesFile: "kafka.properties"

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

jvm:
  opts: "-Xms64M -Xmx256M"
