replicaCount: 1

kafka:
  brokerConnect: "kafka-kafka-bootstrap.strimzi.svc.cluster.local:9092"

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.cryptoviz.epitech-msc2026.me/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.cryptoviz.epitech-msc2026.me/oauth2/start?rd=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User"
  path: /
  pathType: Prefix
  hosts:
    - kafdrop.cryptoviz.epitech-msc2026.me
  tls:
    - secretName: kafdrop-tls
      hosts:
        - kafdrop.cryptoviz.epitech-msc2026.me

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

jvm:
  opts: "-Xms64M -Xmx256M"
